#+HTML_HEAD_EXTRA: <style type="text/css"> .figure object { width: 33%; }</style>

* Grantha

#+begin_center
./grantha.svg
# /grantha/
#+end_center

This is a collection of functions I tend to use. The package aims at
being self-contained, and for that I might copy functions from
elsewhere: which one is worse, dependecy hell or redundancy?

#+begin_quote
- grantha- :: Skt. an artificial arrangement of words, verse, composition,
  treatise, literary production, book in prose or verse, text (opposed
  to artha ‘meaning’).
#+end_quote


** Installation

Tested with ~sbcl~ and ~clisp~.

** list of exported symbols

- ROUND-TO (function) :: Give me either a string or a list of them, and I shall return everything as a list, after converting them to integers. I am the contrary of `int-to-str'.
- LIST-EXPORTED-SYMBOLS-WITH-DOCSTRINGS (function) :: Give me either a string or a list of them, and I shall return everything as a list, after converting them to integers. I am the contrary of `int-to-str'.
- CONCAT (function) :: Give me either a string or a list of them, and I shall return everything as a list, after converting them to integers. I am the contrary of `int-to-str'.
- PADDING (function) :: Give me either a string or a list of them, and I shall return everything as a list, after converting them to integers. I am the contrary of `int-to-str'.
- PRINT-HEX (function) :: Give me either a string or a list of them, and I shall return everything as a list, after converting them to integers. I am the contrary of `int-to-str'.
- LAST-MEMBER (function) :: Give me either a string or a list of them, and I shall return everything as a list, after converting them to integers. I am the contrary of `int-to-str'.
- GET-ODD-ELEMENTS (function) :: Give me either a string or a list of them, and I shall return everything as a list, after converting them to integers. I am the contrary of `int-to-str'.
- TRUNCATE-TIME (function) :: Give me either a string or a list of them, and I shall return everything as a list, after converting them to integers. I am the contrary of `int-to-str'.
- PARSE-TIME (function) :: Give me either a string or a list of them, and I shall return everything as a list, after converting them to integers. I am the contrary of `int-to-str'.
- STR (function) :: Give me either a string or a list of them, and I shall return everything as a list, after converting them to integers. I am the contrary of `int-to-str'.
- HUMAN-READABLE-NUMBER (function) :: Give me either a string or a list of them, and I shall return everything as a list, after converting them to integers. I am the contrary of `int-to-str'.
- PRINT-BIN (function) :: Give me either a string or a list of them, and I shall return everything as a list, after converting them to integers. I am the contrary of `int-to-str'.
- CHAR-TO-INT (function) :: Give me either a string or a list of them, and I shall return everything as a list, after converting them to integers. I am the contrary of `int-to-str'.
- MAKE-PLIST (function) :: Give me either a string or a list of them, and I shall return everything as a list, after converting them to integers. I am the contrary of `int-to-str'.
- INT-TO-STR (function) :: Give me either a string or a list of them, and I shall return everything as a list, after converting them to integers. I am the contrary of `int-to-str'.
- TIME-TO-EXECUTE-AND-RESULT (function) :: Give me either a string or a list of them, and I shall return everything as a list, after converting them to integers. I am the contrary of `int-to-str'.
- INT-TO-CHAR (function) :: Give me either a string or a list of them, and I shall return everything as a list, after converting them to integers. I am the contrary of `int-to-str'.
- CURRENT-DATE-STRING (function) :: Give me either a string or a list of them, and I shall return everything as a list, after converting them to integers. I am the contrary of `int-to-str'.
- SUBTRACT-TIME-OF-DAY (function) :: Give me either a string or a list of them, and I shall return everything as a list, after converting them to integers. I am the contrary of `int-to-str'.
- PRETTY-NUMBER (function) :: Give me either a string or a list of them, and I shall return everything as a list, after converting them to integers. I am the contrary of `int-to-str'.
- PREVIOUS (function) :: Give me either a string or a list of them, and I shall return everything as a list, after converting them to integers. I am the contrary of `int-to-str'.
- TRUNCATE-MEMORY (function) :: Give me either a string or a list of them, and I shall return everything as a list, after converting them to integers. I am the contrary of `int-to-str'.
- GARBAGE-FULL (function) :: Give me either a string or a list of them, and I shall return everything as a list, after converting them to integers. I am the contrary of `int-to-str'.
- GET-EVEN-ELEMENTS (function) :: Give me either a string or a list of them, and I shall return everything as a list, after converting them to integers. I am the contrary of `int-to-str'.
- STR-TO-INT (function) :: Give me either a string or a list of them, and I shall return everything as a list, after converting them to integers. I am the contrary of `int-to-str'.
- NEXT (function) :: Give me either a string or a list of them, and I shall return everything as a list, after converting them to integers. I am the contrary of `int-to-str'.
- ALIAS (function) :: Give me either a string or a list of them, and I shall return everything as a list, after converting them to integers. I am the contrary of `int-to-str'.
- REVERSE-CONS (function) :: Give me either a string or a list of them, and I shall return everything as a list, after converting them to integers. I am the contrary of `int-to-str'.
- CONVERT (function) :: Give me either a string or a list of them, and I shall return everything as a list, after converting them to integers. I am the contrary of `int-to-str'.


** todo

- fix ~human-readable-number~
- make ~current-date-string~ reversible
